random_forest:
  n_estimators: 100
  max_depth: 10
  random_state: 42
  n_jobs: -1

# Future models can be added here
xgboost:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  min_child_weight: 1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
  n_jobs: -1 